export const TYPES = {
  ADD_TASK: 'ADD_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  EDIT_TASK: 'EDIT_TASK',
  STRESS: 'STRESS',
  STRESS_SUPPORT: 'STRESS_SUPPORT',
  STRESS_LEVELS: 'STRESS_LEVELS',
  CONTAINER_COLORS: 'CONTAINER_COLORS'
};
